//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ferti_Add
    {
        public int Id { get; set; }
        public string Shop_name { get; set; }
        public string Taluka { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
    }
}
