//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AddressBookEntities1 : DbContext
    {
        public AddressBookEntities1()
            : base("name=AddressBookEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ferti_Add> Ferti_Add { get; set; }
        public virtual DbSet<Machinery> Machineries { get; set; }
        public virtual DbSet<Pesti_Add> Pesti_Add { get; set; }
        public virtual DbSet<Seed_Add> Seed_Add { get; set; }
        public virtual DbSet<University> Universities { get; set; }
    }
}
